[application]
name = "neco"
version = "0.1.0"
description = "An interpreted programming language."
long_description = "An interpreted programming language."
url = "https://github.com/DanielNos/neco"
license = "OSL-3.0"
gui = false

[desktop_entry]
name = "NeCo"
icon = ""
categories = [ "Utility" ]

[maintainer]
name = "Daniel Nos"
email = "nos.daniel@pm.me"

[build]
target = "."
flags = "-ldflags=\"-w -s\""
platforms = [ "linux/amd64", "linux/386", "linux/arm", "linux/arm64",
              "windows/amd64", "windows/386", "windows/arm", "windows/arm64",
              "darwin/arm64", "darwin/amd64" ]

[deb]
package = true
architectures = [ "amd64", "386", "arm", "arm64" ]

[rpm]
package = true
build_src = true
architectures = [ "amd64", "386", "arm", "arm64" ]

[pkg]
package = true
architectures = [ "amd64" ]

[appimage]
package = true
architectures = [ "amd64" ]
custom_apprun = ""
